name: Setup
description: Perform standard setup and install dependencies using bun.


runs:
  using: composite
  steps:
    - name: Install bun
      uses: oven-sh/setup-bun

    - name: Install dependencies
      shell: bash
      run: bun install
